/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IridescentDebuggerIndexImport } from './routes/iridescent-debugger/index'
import { Route as PostsSlugImport } from './routes/posts.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IridescentDebuggerIndexRoute = IridescentDebuggerIndexImport.update({
  id: '/iridescent-debugger/',
  path: '/iridescent-debugger/',
  getParentRoute: () => rootRoute,
} as any)

const PostsSlugRoute = PostsSlugImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugImport
      parentRoute: typeof rootRoute
    }
    '/iridescent-debugger/': {
      id: '/iridescent-debugger/'
      path: '/iridescent-debugger'
      fullPath: '/iridescent-debugger'
      preLoaderRoute: typeof IridescentDebuggerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/iridescent-debugger/': typeof IridescentDebuggerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$slug' | '/iridescent-debugger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$slug' | '/iridescent-debugger'
  id: '__root__' | '/' | '/posts/$slug' | '/iridescent-debugger/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSlugRoute: typeof PostsSlugRoute
  IridescentDebuggerIndexRoute: typeof IridescentDebuggerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSlugRoute: PostsSlugRoute,
  IridescentDebuggerIndexRoute: IridescentDebuggerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$slug",
        "/iridescent-debugger/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$slug": {
      "filePath": "posts.$slug.tsx"
    },
    "/iridescent-debugger/": {
      "filePath": "iridescent-debugger/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
