/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IridescentDebuggerIndexImport } from './routes/iridescent-debugger/index'
import { Route as AsciiIndexImport } from './routes/ascii/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IridescentDebuggerIndexRoute = IridescentDebuggerIndexImport.update({
  id: '/iridescent-debugger/',
  path: '/iridescent-debugger/',
  getParentRoute: () => rootRoute,
} as any)

const AsciiIndexRoute = AsciiIndexImport.update({
  id: '/ascii/',
  path: '/ascii/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ascii/': {
      id: '/ascii/'
      path: '/ascii'
      fullPath: '/ascii'
      preLoaderRoute: typeof AsciiIndexImport
      parentRoute: typeof rootRoute
    }
    '/iridescent-debugger/': {
      id: '/iridescent-debugger/'
      path: '/iridescent-debugger'
      fullPath: '/iridescent-debugger'
      preLoaderRoute: typeof IridescentDebuggerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiIndexRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiIndexRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ascii/': typeof AsciiIndexRoute
  '/iridescent-debugger/': typeof IridescentDebuggerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascii' | '/iridescent-debugger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascii' | '/iridescent-debugger'
  id: '__root__' | '/' | '/ascii/' | '/iridescent-debugger/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsciiIndexRoute: typeof AsciiIndexRoute
  IridescentDebuggerIndexRoute: typeof IridescentDebuggerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsciiIndexRoute: AsciiIndexRoute,
  IridescentDebuggerIndexRoute: IridescentDebuggerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ascii/",
        "/iridescent-debugger/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ascii/": {
      "filePath": "ascii/index.tsx"
    },
    "/iridescent-debugger/": {
      "filePath": "iridescent-debugger/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
