/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IridescentDebuggerIndexImport } from './routes/iridescent-debugger/index'
import { Route as AsciiIndexImport } from './routes/ascii/index'
import { Route as AsciiInputImport } from './routes/ascii/input'
import { Route as AsciiDocsImport } from './routes/ascii/docs'
import { Route as AsciiAnimationsImport } from './routes/ascii/animations'
import { Route as AsciiArticlesSlugImport } from './routes/ascii/articles.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IridescentDebuggerIndexRoute = IridescentDebuggerIndexImport.update({
  id: '/iridescent-debugger/',
  path: '/iridescent-debugger/',
  getParentRoute: () => rootRoute,
} as any)

const AsciiIndexRoute = AsciiIndexImport.update({
  id: '/ascii/',
  path: '/ascii/',
  getParentRoute: () => rootRoute,
} as any)

const AsciiInputRoute = AsciiInputImport.update({
  id: '/ascii/input',
  path: '/ascii/input',
  getParentRoute: () => rootRoute,
} as any)

const AsciiDocsRoute = AsciiDocsImport.update({
  id: '/ascii/docs',
  path: '/ascii/docs',
  getParentRoute: () => rootRoute,
} as any)

const AsciiAnimationsRoute = AsciiAnimationsImport.update({
  id: '/ascii/animations',
  path: '/ascii/animations',
  getParentRoute: () => rootRoute,
} as any)

const AsciiArticlesSlugRoute = AsciiArticlesSlugImport.update({
  id: '/ascii/articles/$slug',
  path: '/ascii/articles/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ascii/animations': {
      id: '/ascii/animations'
      path: '/ascii/animations'
      fullPath: '/ascii/animations'
      preLoaderRoute: typeof AsciiAnimationsImport
      parentRoute: typeof rootRoute
    }
    '/ascii/docs': {
      id: '/ascii/docs'
      path: '/ascii/docs'
      fullPath: '/ascii/docs'
      preLoaderRoute: typeof AsciiDocsImport
      parentRoute: typeof rootRoute
    }
    '/ascii/input': {
      id: '/ascii/input'
      path: '/ascii/input'
      fullPath: '/ascii/input'
      preLoaderRoute: typeof AsciiInputImport
      parentRoute: typeof rootRoute
    }
    '/ascii/': {
      id: '/ascii/'
      path: '/ascii'
      fullPath: '/ascii'
      preLoaderRoute: typeof AsciiIndexImport
      parentRoute: typeof rootRoute
    }
    '/iridescent-debugger/': {
      id: '/iridescent-debugger/'
      path: '/iridescent-debugger'
      fullPath: '/iridescent-debugger'
      preLoaderRoute: typeof IridescentDebuggerIndexImport
      parentRoute: typeof rootRoute
    }
    '/ascii/articles/$slug': {
      id: '/ascii/articles/$slug'
      path: '/ascii/articles/$slug'
      fullPath: '/ascii/articles/$slug'
      preLoaderRoute: typeof AsciiArticlesSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascii/animations': typeof AsciiAnimationsRoute
  '/ascii/docs': typeof AsciiDocsRoute
  '/ascii/input': typeof AsciiInputRoute
  '/ascii': typeof AsciiIndexRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
  '/ascii/articles/$slug': typeof AsciiArticlesSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascii/animations': typeof AsciiAnimationsRoute
  '/ascii/docs': typeof AsciiDocsRoute
  '/ascii/input': typeof AsciiInputRoute
  '/ascii': typeof AsciiIndexRoute
  '/iridescent-debugger': typeof IridescentDebuggerIndexRoute
  '/ascii/articles/$slug': typeof AsciiArticlesSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ascii/animations': typeof AsciiAnimationsRoute
  '/ascii/docs': typeof AsciiDocsRoute
  '/ascii/input': typeof AsciiInputRoute
  '/ascii/': typeof AsciiIndexRoute
  '/iridescent-debugger/': typeof IridescentDebuggerIndexRoute
  '/ascii/articles/$slug': typeof AsciiArticlesSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascii/animations'
    | '/ascii/docs'
    | '/ascii/input'
    | '/ascii'
    | '/iridescent-debugger'
    | '/ascii/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascii/animations'
    | '/ascii/docs'
    | '/ascii/input'
    | '/ascii'
    | '/iridescent-debugger'
    | '/ascii/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/ascii/animations'
    | '/ascii/docs'
    | '/ascii/input'
    | '/ascii/'
    | '/iridescent-debugger/'
    | '/ascii/articles/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsciiAnimationsRoute: typeof AsciiAnimationsRoute
  AsciiDocsRoute: typeof AsciiDocsRoute
  AsciiInputRoute: typeof AsciiInputRoute
  AsciiIndexRoute: typeof AsciiIndexRoute
  IridescentDebuggerIndexRoute: typeof IridescentDebuggerIndexRoute
  AsciiArticlesSlugRoute: typeof AsciiArticlesSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsciiAnimationsRoute: AsciiAnimationsRoute,
  AsciiDocsRoute: AsciiDocsRoute,
  AsciiInputRoute: AsciiInputRoute,
  AsciiIndexRoute: AsciiIndexRoute,
  IridescentDebuggerIndexRoute: IridescentDebuggerIndexRoute,
  AsciiArticlesSlugRoute: AsciiArticlesSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ascii/animations",
        "/ascii/docs",
        "/ascii/input",
        "/ascii/",
        "/iridescent-debugger/",
        "/ascii/articles/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ascii/animations": {
      "filePath": "ascii/animations.tsx"
    },
    "/ascii/docs": {
      "filePath": "ascii/docs.tsx"
    },
    "/ascii/input": {
      "filePath": "ascii/input.tsx"
    },
    "/ascii/": {
      "filePath": "ascii/index.tsx"
    },
    "/iridescent-debugger/": {
      "filePath": "iridescent-debugger/index.tsx"
    },
    "/ascii/articles/$slug": {
      "filePath": "ascii/articles.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
